### ISSUE TITLE
mb labs retargeting Issue, please help

### ISSUE THREAD

**Issue by cgbegin** [cgvirus/Simple-Retarget-Tool-Blender#2]
Can you please tell me what I am doing wrong here.
Thank you

https://user-images.githubusercontent.com/98581106/151510499-c58564a9-5add-4568-9f81-621d6e9a8f94.mp4

https://user-images.githubusercontent.com/98581106/151512085-1ad8d51c-84c5-4359-8bba-0df223097d3d.mp4

https://user-images.githubusercontent.com/98581106/151513079-4f3ce211-1093-4911-84b7-e5a4409155ac.mp4

**Comment by cgvirus** [comment]
Hi can you send the running.fbx here? I can't understand clearly the issue as the videos are slightly corrupted,

**Comment by cgbegin** [comment]
The file is attached, although this happens with every fbx i download from
mixamo. thank you

**Comment by cgvirus** [comment]
Ok, thank you. Investigating

**Comment by cgvirus** [comment]
Does MB lab have blender 3.0 support? Which one is latest and with which Blender version? I am seeing a finalize bug in Blender 3.0

**Comment by cgbegin** [comment]
I think 2.91 is the latest with support

**Comment by cgvirus** [comment]
Should be solved. Feel free to open again if needed. Thanks.
https://youtu.be/uW77m8Yuuz4

**Comment by cgbegin** [comment]
Thank you very match man. Will check as soon as I get home. Much appreciated for the feedback. You rock
