### ISSUE TITLE
Bone roll orientation problem

### ISSUE THREAD

**Issue by carbon-seven** [cgvirus/Simple-Retarget-Tool-Blender#3]
I am using blender 3.1 and the mixamo and rigify armatures have 90 degrees tilted bone orientations along both of the arms. 

Steps to reproduce behaviour:
1. Create a rigify armature
2. Import a mixamo fbx with apply transform, manual orientation ticked off, tick automatic orientation.
3. turn on axes display in the armature object data properties.
4. Compare the 2 rigs.

Expected behaviour: Just like the latest tutorial on youtube, there should be no bone orientation problems and bones should match each other.

Screenshots:
![image](https://user-images.githubusercontent.com/102753608/172007011-a9905e25-f998-411d-9560-4c5d8578d002.png)
Rigify on left and mixamo on right
![image](https://user-images.githubusercontent.com/102753608/172007051-d541cdd2-e581-4b6a-9488-2d36d4800da3.png)
My import settings

Thank you.

**Comment by cgvirus** [comment]
Hi, start re targeting the muscle bones. The code is already included to re orient the target. (BONE ROLL)
![pre](https://user-images.githubusercontent.com/22106885/172010202-a78da98e-0b85-4ead-84d2-a83fb5b529da.png)
![post](https://user-images.githubusercontent.com/22106885/172010200-d3184805-ef20-4333-af67-31aed7d5fb75.png)

**Comment by cgvirus** [comment]
Hi, if it is solved, please close the issue. Otherwise let me know. Thanks.

**Comment by carbon-seven** [comment]
Thank you Mr Fahad! Is it possible to retarget Mixamo mocap to Vroid VRM(converted to glb) files with simple retarget tool?  Does the addon contain code to correct any bone orientations from any armature(beside rigify armature) to the source mixamo bone orientation?

**Comment by cgvirus** [comment]
Yes should be possible. If not then let me know with a sample file. Thanks.
