### ISSUE TITLE
new to blender

### ISSUE THREAD

**Issue by langleyq** [cgvirus/Simple-Retarget-Tool-Blender#4]
the retargeting works amazing for me, however when i delete the mixamo motion the animation of the retargeted bone is removed as well, what can i do to keep the animation?

https://user-images.githubusercontent.com/61494866/186193964-e23639f9-650e-4cfe-baf7-f5e136860573.mp4

**Comment by cgvirus** [comment]
Hi, no need to delete the mixamo rig. just hide it when not needed. use action editor to replace the animation shown in the tutorial. To export fbx use selected only.

**Comment by cgvirus** [comment]
Closing as inactive and not a bug.
