### ISSUE TITLE
Retargeting is not applied correctly 

### ISSUE THREAD

**Issue by Nico3652** [cgvirus/Simple-Retarget-Tool-Blender#5]
Hi thanks for your work 

I've followed your [tutorial](https://www.youtube.com/watch?v=uW77m8Yuuz4)  and I tried to reproduce the same process than yours in the tuto . I downloaded a simple running animation on Maximo and imported it correctly (remove rotation...).
Then I created the char with MBLab -> go to T pose mode and start by 'retargeting root' the middle bone as you did with unlocked position. 

The problem came when I 'm trying to retarget top muscle (arm), it seems like bone are distorted compare to model armature and can't find why :

<img width="496" alt="Capture d’écran 2022-10-02 à 11 27 09" src="https://user-images.githubusercontent.com/50270977/193447431-0633eaac-2c69-4d06-97e3-7749cff38a32.png">

I started over again multiple times before writing this issue but every time I've got the same result. 

Questions :

- Could you know what am I missing here ? 
- The add-on could not support all armature ? 

Here is the blend file if needed

[retargeting_test.blend.zip](https://github.com/cgvirus/Simple-Retarget-Tool-Blender/files/9692131/retargeting_test.blend.zip)

 
I'm still not very experimented with blender so thanks for any help

**Comment by cgvirus** [comment]
Hi your mb lab character is not is T-Pose. It's in star pose. You need to finalize it with T-Pose before starting retargeting. See this.
https://youtu.be/oLf4sycl7mA

**Comment by Nico3652** [comment]
Thanks for reply. 

Ok my mistake was to think that the finalize step was not important. 
I can't finalize because I'm getting a Python error every time when I click finalize with blender 3.2.2 : 

<img width="873" alt="Capture d’écran 2022-10-02 à 23 04 15" src="https://user-images.githubusercontent.com/50270977/193476250-33e98f81-4671-4691-9fb0-f65e4e3a2ec9.png">

Did you already have this error ? Otherwise thank you I m going to close this

**Comment by cgvirus** [comment]
use mblab latest release from github. 
https://github.com/animate1978/MB-Lab/releases
