### ISSUE TITLE
Leg bone retarget issue (other bones OK)

### ISSUE THREAD

**Issue by SlurmsMack** [cgvirus/Simple-Retarget-Tool-Blender#8]
Hi cgvirus, first of all your add-on is great so thank you for sharing it.

I am running into some retargeting issues on a number of rigs, this one seems to have been made in Daz. Images below are showing the FK bones. 

I am able to retarget the other bones successfully, even though the source armature (Mixamo) is in T pose and the target armature is in A pose, some slight adjustments made this work.

The leg bones however have an error and I can't seem to be able to fix it. It seems they are on a different axis but I struggle to understand why it would work for the other bones in the rig but not the leg bones.

Any help would be greatly appreciated.

Thanks

Rig after sucessful arm bone retargeting
![arms](https://github.com/cgvirus/Simple-Retarget-Tool-Blender/assets/169738287/afa4691d-baa0-4639-8a5a-eda55e245c65)

Rig after unsuccessful leg bone retarget
![legs](https://github.com/cgvirus/Simple-Retarget-Tool-Blender/assets/169738287/9a69c86b-896f-4708-ae15-b76e5b43aa77)

**Comment by cgvirus** [comment]
Hi, please send the other rig to inspect. Will return to you tomorrow. Thanks.

**Comment by SlurmsMack** [comment]
Thanks so much, the link is below:

[https://we.tl/t-IncphY0MdN](https://we.tl/t-IncphY0MdN?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

**Comment by SlurmsMack** [comment]
Hey, just checking if you got this as the link may have expired. Do you need me to send another one?

**Comment by cgvirus** [comment]
Hi, I got some high fever. Will look into it after recovery. Got the file. Thanks.

**Comment by SlurmsMack** [comment]
No worries at all, and no rush either. Hope you feel better soon!

**Comment by cgvirus** [comment]
Hi can you export the character with T pose from Daz. Also if of you can send me the FBX of the character as well.

**Comment by cgvirus** [comment]
So far What I am seeing:
- You need to export T pose From Daz or if you are using Daz to blender bridge plugin you will need to do give it a Tpose there.
- Then disable IK
- Then retarget. I was successfully able to retarget the leg without problem, but may be if you can provide Tpose as rest pose I can check it further. 


Since Daz plugin creates way too much driver and dependencies, my rest pose creator for some reason can't create the rest pose for this character. I am also getting a lot of invalid driver issues in blender in your character. Snap here:

![Screenshot from 2024-05-21 03-46-10](https://github.com/cgvirus/Simple-Retarget-Tool-Blender/assets/22106885/7a8b8bfc-4d40-4aa9-86eb-854539da9d98)

**Comment by SlurmsMack** [comment]
I would send if I could, unfortunately I received this model from the owner's patreon and I don't have access to their original DAZ model.

However, I believe I have (by chance) stumbled across a solution/workaround. After the retarget is applied, I played around with the settings in the target bone's bone constraints menu. After setting the Target to "Local Space (Owner Orientation)", the leg bones orientation matched the source bone. Seems quite simple but I wasn't looking at the constraints menu, bit silly of me. 

Still a lit of bit of tweaking remained, for example when retargeting the source hip bone to the target root bone for this type of armature, you have to turn the influence of the rotation to zero to stop it from swaying side to side.

I hope this solution helps other people, from my perspective, I consider the issue closed. 

![solution 2](https://github.com/cgvirus/Simple-Retarget-Tool-Blender/assets/169738287/21579a18-984d-4ba9-95d9-c66515eb5e9d)

**Comment by cgvirus** [comment]
Well, it might work for one animation like walking but it will not work for others like sitting. 
Anyway, as you don't have the raw daz character, I think it will not be possible to debug.
I will try to recreate the scenario within daz in some other machine. There mechanism as far as I have heard is kinda weird though. Let's see.

**Comment by SlurmsMack** [comment]
That's true I haven't tried this with another animations, I'll look forward to anything you come up with. Thank you very much for looking into this, much appreciated
