### ISSUE TITLE
After retarget (followed video for simple retarget/mblab) model is warped

### ISSUE THREAD

**Issue by mbowles201** [cgvirus/Simple-Retarget-Tool-Blender#9]
After remapping root and bone muscles, animations from mixamo were great.  Saved, closed Blender.  When reopened and opened blend file, model is warped and no longer matching prior work.

**Comment by cgvirus** [comment]
Hi, can you send a sample?

**Comment by mbowles201** [comment]
[first_model.zip](https://github.com/user-attachments/files/16762230/first_model.zip)
Here it is, no textures though, file is too large for github if they are included.

**Comment by cgvirus** [comment]
I think you have not finalized the character yet. Watch this chapter fully.
https://youtu.be/uW77m8Yuuz4?t=88&si=A4CV_KGnFdjHULqM

[finalized.zip](https://github.com/user-attachments/files/16763091/finalized.zip)

**Comment by mbowles201** [comment]
I made character, finalized (per video at that chapter) then did the animation retargeting.  Are you saying finalize again?  I tried that and it severely warped the model.  
And do we just select our model and export to whatever format to use in tools like godot, unreal, etc?

**Comment by cgvirus** [comment]
What does my version resulting in your system?
You need to bake the animation first then export to other engines.

**Comment by mbowles201** [comment]
You r version works in blender and allows me to edit, save, close and reopen.  Thanks.  I need to check on the baking and then removal of the imported fbx.

**Comment by mbowles201** [comment]
as a side question, once baked do you have to keep the fbx skeleton you retargeted from and can you add other animations?

**Comment by cgvirus** [comment]
I would suggest to start a fresh file. I don't know what has happened with your file. Took me a while to debug. At the end I started fresh. Thought it's a blender bug!
Your file has corrupted action editor curves. Start fresh. Here is the tut. 
NOTE: your preset also has name problem, should be "mixamorig".

https://drive.google.com/file/d/14d5fqkdhNY4UKMHJQPZkR3se9y1UTzZx/view?usp=sharing
Let me know when download is completed. Thanks.

**Comment by mbowles201** [comment]
Got it, going to fire it up.   I think I got the mixamorg1 because I deleted the initial fbx walk skeleton then re-added.

**Comment by mbowles201** [comment]
I started from scratch.  When you add the dance fbx, then rename it and same, then you delete the dance fbx from the scene.  You then change to the left side skeleton and change the action to dance and your models snap to that rig.  Mine does nothing there.  I have a run action that snow the yellow keyframes in the action editor and neither model changes, nor does the animation work.

**Comment by cgvirus** [comment]
What is you Blender version? Which OS? Mb-Lab Version?

**Comment by mbowles201** [comment]
BLender 4.2.1, windows 10, mb-lab 1.8.1

**Comment by cgvirus** [comment]
Hmm. Then IDK.

**Comment by mbowles201** [comment]
yeah, its strange.   I select the armature on the left (the walking fbx), then import the next animation fbx.   Rename in the action screen, then delete it.   I dont get the same results.  Very odd.

**Comment by cgvirus** [comment]
Do one thing. 
> Create a brand new project
> Import both FBX files only.
> Then test with the action.

**Comment by mbowles201** [comment]
ok, new project, imported walk and run fbx.
selected walk, named it walk.
selected run, named it run.  

walk just one walks
run, one walks, other runs...

**Comment by cgvirus** [comment]
HUH!
I am out bruh! Best of luck!
:')

**Comment by mbowles201** [comment]
I noticed the second anim I bring in following your video, all the armatrue bones are names **mixamorig1**  and not **mixamorig**

**Comment by cgvirus** [comment]
I think you need to load factory reset in Blender.
Edit>pref>hamburger>load factory reset.

May be some addon is misbehaving. Also try other versions of blender like 4.1.
Action editor should work by default.

**Comment by mbowles201** [comment]
BINGO!   I did a bulk rename of the new bones to **mixamorig** (removing the 1) like you did for the txt file, and now I have walk and run working!!  Thanks!

**Comment by mbowles201** [comment]
Going to have to call it quits.   Cant follow what you did to set up and do the second animation bake.   Appreciate your efforts.
